
services:
  - type: web
    name: adamaloportfolio
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
    buildFilter:
      paths:
        - src/**
        - public/**
        - index.html
        - package.json
        - vite.config.ts
        - tailwind.config.ts
